enableGlobalCache: false

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

npmRegistryServer: 'https://nexus.toss.bz/repository/npm-group/'

unsafeHttpWhitelist:
  - 'nexus.toss.bz'
