changesetBaseRefs:
  - HEAD

enableGlobalCache: false

npmScopes:
  jsr:
    npmRegistryServer: 'https://npm.jsr.io'

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
