name: Changeset Bot

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: changesets/bot@e755cedfffdc49f54ce5daa69d960a143941b787 # master
